### ISSUE TITLE
Agency Report Submission - Database Changes

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/cpf-reporter#132]
### Why is this issue important?

See User Story here https://github.com/usdigitalresponse/cpf-reporter/issues/73

This is an issue in the sequence of tickets to ensure the CPF reporter can accept a user-submitted upload file and receive feedback on any errors that are present in the submitted file data.

### Blocks

- [x] #135

### Blocked By
None

### Current State

There are some tables available in the database that capture the upload validation data, but they are now outdated.

### Expected State

1. Ensure the latest database schema aligns with the Lucid Chart diagram here. Some of these changes may already exist in which case please verify it matches the ticket requirements.
2. Add a constraint in the `UploadValidation` table which ensures that for any `uploadId` there can only be one record where `results` is `null`.

<img width="604" alt="image" src="https://github.com/usdigitalresponse/cpf-reporter/assets/6497366/26035eac-fa56-4771-b582-dc1d6b15b0ba">
<img width="610" alt="image" src="https://github.com/usdigitalresponse/cpf-reporter/assets/6497366/8cbd05cc-c8c3-4d3c-ba05-b08d63038713">

### Implementation Plan
Note: we are not implementing `ValidationRules` table for this V1 April 10th deadline.
```
// schema.prisma

// Rename Upload to UploadFile and edit the fields
model UploadFile {
  id                    Int                  @id @default(autoincrement())
  filename              String
  uploadedById          Int
  uploadedBy            User                 @relation(fields: [uploadedById], references: [id])
  agencyId              Int
  agency                Agency               @relation(fields: [agencyId], references: [id])
  reportingPeriodId     Int
  reportingPeriod       ReportingPeriod      @relation(fields: [reportingPeriodId], references: [id])
  expenditureCategoryId Int?
  expenditureCategory   ExpenditureCategory? @relation(fields: [expenditureCategoryId], references: [id])
  createdAt             DateTime             @default(now()) @db.Timestamptz(6)
  updatedAt             DateTime             @default(now()) @db.Timestamptz(6)
  validations           UploadValidation[]
}

model UploadValidation {
  id                  Int            @id @default(autoincrement())
  uploadId            Int
  upload              Upload         @relation(fields: [uploadId], references: [id])
  passed                bool
  results                Json?         @db.JsonB
  initiatedById          Int
  initiatedBy            User                 @relation(fields: [initiatedById], references: [id])
  createdAt           DateTime      @default(now()) @db.Timestamptz(6)
  updatedAt           DateTime      @default(now()) @db.Timestamptz(6)
}
```

2. To add constraint:
Create a blank prisma migration file
```
npx prisma migrate dev -n add_UploadValidation_constraint --create-only
```
add the following SQL
```
CREATE UNIQUE INDEX unique_null_results_per_uploadid ON UploadValidation (uploadId)
WHERE results IS NULL;
```
Run migration
```
prisma migrate dev
```

3. Add a test case in `services/uploadValidations/uploadValidations.test.ts`
The test should call `createUploadValidation` twice for the same `uploadId` with  `results: null` and expect an error.

**Comment by laurelkorwin** [comment]
I've made the prisma changes & migrated without issue but now trying to update the GraphQL types, mutation / query resolvers etc brings up an issue in `Uploads.tsx` since the new schema doesn't include `validatedAt` or `invalidatedAt`, which power the logic [here](https://github.com/usdigitalresponse/cpf-reporter/blob/527a3eb2b71bd008c91f7ebf9585ea07ef4a88fb/web/src/components/Upload/Uploads/Uploads.tsx#L24)

Should we be using some combination of `updatedAt` and `passed` to calculate these dates instead? Remove this logic altogether? Or wondering if we should leave those fields in? @as1729

**Comment by laurelkorwin** [comment]
Update:

Most of this ticket is done -- remaining items are:
- Renaming `Upload` to `UploadFile`
- Removing `subrecipients` on `Upload` / `UploadFile`
- Removing `organization` on `Upload` / `UploadFile`

I have been splitting things out and left those for last because they result in a _lot_ of type changes, dead code etc. that needs to be removed. If those changes are necessary for testing with partners on 4/10, I can remove myself from this ticket for someone else to close out. If not / if the other changes from this ticket will suffice, I'm happy to keep it and work on it again when back the week of 4/8
