### ISSUE TITLE
[Issue]: View-only Subrecipient Tab

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/cpf-reporter#368]
### Why is this issue important?

It is very difficult to test functionality around up-to-date information for subrecipients. Currently the only way would be to generate treasury files which is time consuming and limited as you would only see net new subrecipients in the report.

### Current State

There is no way to see a list of subrecipients and information about them in the CPF reporter

### Expected State
Table should follow format of the table on Upload page (i.e. similar filter and sorting)

- The USDR Admin user role will see a tab named "Subrecipients." This will not be visible to the Organization Admin and Organization Staff roles.
- The Subrecipient tab will be read-only.
- When you go to the "Subrecipients" tab, a table will display each subrecipient in a row based on each unique UEI/TIN combination
- The following columns will display for each subrecipient
   - UEI
   - TIN
   - Details - this will a list of the following fields. If no values exist, it will display as blank after the field name
      - Name
      - Recipient ID
      - POC Name
      - POC Phone number
      - POC Email Address
      - Zip5
      - Zip4
      - Address Line 1
      - Address Line 2
      - Address Line 3
      - City
      - State
   - Created Date - this will reflect the date the subrecipient was first created via a valid upload file
   - Last Updated Date - this should display the date of the last valid upload where the subrecipient was both include, and where one or more of the fields related to the subrecipient changed
   - Upload Links
      - First line should display the text "Lastest upload: [file name text with link to last valid upload that included the UEI/TIN combo]" - 
      - Followed by "Other uploads" - this should display a list of all fileanmes with upload links for all valid uploads that include the UEI/TIN combo

**Visual of Table Display**
note - this is to demonstrate the expected content display; design of the table should mirror the table on the uploads page
![image](https://github.com/user-attachments/assets/1e83ffc1-e934-488a-a7c6-e8edbe739806)

**Comment by Vikariusu** [comment]
@ClaireValdivia I have a few clarifying questions:

1. Does the upload link direct to the CPF's upload detail page (`/uploads/:id`), or is it a link that allows for file download?
2. The created/updated date in the attached screenshot follows the mm/dd/yyyy format. However, the format used on the uploads page is "Dec 13th 2023, 1:32:32 PM". Should we:
a) Reuse the format from the uploads page?
b) Use the mm/dd/yyyy format on the Subrecipients page? If so, should we exclude the time and display the date only?
3. Are both UEI and TIN values strictly numeric, or can they contain alphabetic or special characters?

**Comment by ClaireValdivia** [comment]
@Vikariusu 
1 - ideally it would be a link to download the file
2 - good catch! Let's use the same date format that is on the upload page
3 - They can be alphanumeric, we just require a fixed string length (12 for uei, 9 for tin). We don't expect special characters but I don't believe we have a validation in place to prevent them.

**Comment by as1729** [comment]
Weronika Tomaszewska (ET, she/her)
  2:15 PM
Hi, quick question - if there are 2 subrecipient uploads: one created on Monday and one created on Tuesday, and on Wednesday there’s a change to the one on Monday, which upload is the latest? The one uploaded on Tuesday (sorted by createdAt), or the one created on Monday (sorted by updatedAt)?




NEW



aditya
:spiral_calendar_pad:  [2:41 PM](https://usdigitalresponse.slack.com/archives/D06A3PEP94M/p1723574514484589)
Sorted by updatedAt and in this case it will be back to the upload created on Monday but updated on Wednesday
[2:43](https://usdigitalresponse.slack.com/archives/D06A3PEP94M/p1723574580438209)
One thing to note is that these uploads must be validated (most recent UploadValidation record must be valid)


Weronika Tomaszewska (ET, she/her)
  3:03 PM
Okay, so:
The latestSubrecipientUpload is the subrecipientUpload with the latest updatedAt AND with latestSubrecipientUpload.upload.latestValidation === passed.
What if the last updated upload has 2 validations, one that passed (first one), one that didn’t (latest one). Would this scenario happen in the future when users can invalidate uploads?
From what I understand, subrecipient is created via file upload therefore there'll be always at least 1 subrecipient upload assigned to a subrecipient. What if the validation on this file doesn’t pass? Or does it have to pass to even create a subrecipient?


aditya
:spiral_calendar_pad:  [3:07 PM](https://usdigitalresponse.slack.com/archives/D06A3PEP94M/p1723576070704189)
What if the last updated upload has 2 validations, one that passed (first one), one that didn’t (latest one). Would this scenario happen in the future when users can invalidate uploads?
If the latest validation of the upload is invalid, then we should not display this upload as the latest upload. If it is not too much scope creep then I would recommend that we display this in the front-end as “invalidated upload 123”
[3:08](https://usdigitalresponse.slack.com/archives/D06A3PEP94M/p1723576133319429)
What if the validation on this file doesn’t pass? Or does it have to pass to even create a subrecipient?
It must pass before a subrecipient is created in the database. However, it is possible that the upload is invalidated (functionality not implemented yet) at a later time. When we are implementing upload invalidation we will update the subrecipient page to accommodate these changes


Weronika Tomaszewska (ET, she/her)
  3:58 PM
In that case, would it make sense for the latestSubrecipientUpload to return the latest subrecipientUpload (sorted by updatedAt) even if the latest validation on that upload is invalid?
Attaching screenshots, let me know if this what you had in mind.
2 files
 
invalid latest upload validation.png


valid latest upload validation.png




aditya
:spiral_calendar_pad:  [4:03 PM](https://usdigitalresponse.slack.com/archives/D06A3PEP94M/p1723579392119879)
If possible, I think this would be a good middle-ground
Latest Valid Upload
Other Vaild Uploads
All Other Uploads (ordered by updated at regardless of validity with invalid uploads prefixed with “[invalid]“)
[4:03](https://usdigitalresponse.slack.com/archives/D06A3PEP94M/p1723579419745459)
The three points above will correspond to three sections on the right with bold headers
4:04
For some subrecipients it could be possible that 1 and 2 are empty while 3 has an invalid upload


Weronika Tomaszewska (ET, she/her)
  4:14 PM
Okay, I can do that. And with "details" and "last updated date" columns - those will access the latest valid subrecipient upload?


aditya
:spiral_calendar_pad:  4:23 PM
correct
[4:24](https://usdigitalresponse.slack.com/archives/D06A3PEP94M/p1723580648759629)
if sections 1 and 2 are empty on the “Upload Links” column then Details and Last Updated Date will be empty as well


Weronika Tomaszewska (ET, she/her)
  4:24 PM
makes sense, thanks!


aditya
:spiral_calendar_pad:  4:26 PM
just to note its possible that as we develop the invalidate upload feature that we might re-add the Details section for subrecipients that are not tied to any valid uploads, but since there is too much ambiguity on that, its better to leave it empty for now and address it when we scope out the other feature
:+1:
1

**Comment by ClaireValdivia** [comment]
from convo with Aditya:
add in "Invalid uploads" to right column. this will cover scenario where subrecipient no longer has valid uploads. will update issue and mockup to reflect
